ingress:
  enabled: true
  annotations:
    external-dns.alpha.kubernetes.io/ingress-hostname-source: annotation-only
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: basic-auth
    nginx.ingress.kubernetes.io/auth-realm: "Authentication Required"
  ingressClassName: nginx
  hosts:
    - host: qdrant.{{{DOMAIN}}}
      paths:
        - path: /
          pathType: Prefix
          servicePort: 6333

resources:
  requests:
    cpu: 1 
    memory: 2Gi
  limits:
    memory: 2Gi