# https://github.com/Milvus-io/Milvus/issues/40267
# Ingress expodes service port, not 9091 web UI port
# ingress:
#   enabled: true
#   annotations:
#     external-dns.alpha.kubernetes.io/ingress-hostname-source: annotation-only
#     nginx.ingress.kubernetes.io/auth-type: basic
#     nginx.ingress.kubernetes.io/auth-secret: basic-auth
#     nginx.ingress.kubernetes.io/auth-realm: "Authentication Required"
#   ingressClassName: nginx
#   rules:
#     - host: Milvus.{{{DOMAIN}}}
#       path: /
#       pathType: Prefix

cluster:
  enabled: false

serviceAccount:
  create: true

etcd:
  replicaCount: 1
  resources:
    requests:
      cpu: 200m    
      memory: 256Mi
    limits:
      memory: 256Mi

minio:
  enabled: false
  externalS3:
    enabled: true
    host: "s3.{{AWS_REGION}}.amazonaws.com"
    port: "443"
    useSSL: true
    bucketName: "{{MILVUS_BUCKET_NAME}}"
    rootPath: "milvus"
    useIAM: true
    cloudProvider: "aws"
    region: "{{AWS_REGION}}"

pulsarv3:
  components:
    autorecovery: false
  zookeeper:
    replicaCount: 1
    resources:
      requests:
        cpu: 200m    
        memory: 256Mi
      limits:
        memory: 256Mi
  broker:
    replicaCount: 1
    resources:
      requests:
        cpu: 500m    
        memory: 2Gi
      limits:
        memory: 2Gi
    configData:
      autoSkipNonRecoverableData: "true"
      managedLedgerDefaultEnsembleSize: "1"
      managedLedgerDefaultWriteQuorum: "1"
      managedLedgerDefaultAckQuorum: "1"
  proxy:
    replicaCount: 1
    resources:
      requests:
        cpu: 500m    
        memory: 1Gi
      limits:
        memory: 1Gi
  bookkeeper:
    replicaCount: 1
    resources:
      requests:
        cpu: 500m    
        memory: 2Gi
      limits:
        memory: 2Gi
