apiVersion: apps/v1
kind: Deployment
metadata:
  name: deepseek-r1-llama-8b-int8-neuron
  namespace: vllm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deepseek-r1-llama-8b-int8-neuron
  template:
    metadata:
      labels:
        app: deepseek-r1-llama-8b-int8-neuron
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      automountServiceAccountToken: false
      nodeSelector:
        eks.amazonaws.com/instance-family: inf2
        {{#if compile}}
        node.kubernetes.io/instance-type: inf2.8xlarge 
        karpenter.sh/capacity-type: on-demand
        {{else}}
        node.kubernetes.io/instance-type: inf2.xlarge
        {{/if}}
      containers:
        - name: vllm
          image: public.ecr.aws/neuron/pytorch-inference-vllm-neuronx:0.9.1-neuronx-py310-sdk2.25.0-ubuntu22.04
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - NET_RAW
            seccompProfile:
              type: RuntimeDefault
          command: ["vllm", "serve"]
          args:
            - deepseek-ai/DeepSeek-R1-Distill-Llama-8B
            - --served-model-name=deepseek-r1-llama-8b-int8-neuron
            - --trust-remote-code
            - --gpu-memory-utilization=0.90
            # - --max-model-len=32768 # 32K
            # DeepSeek-R1 specific
            - --reasoning-parser=deepseek_r1
            # Neuron specific
            - --tensor-parallel-size=2
            - --max-num-seqs=4
            - --max-model-len=8192 #8K
            {{#unless compile}}
            - '--override-neuron-config={"quantized": true, "quantized_checkpoints_path": "/root/.cache/huggingface/hub/models--deepseek-ai--DeepSeek-R1-Distill-Llama-8B/snapshots/6a6f4aa4197940add57724a7707d069478df56b1", "kv_cache_quant": true}'
            {{/unless}}
          env:
            - name: HUGGING_FACE_HUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: hf-token
                  key: token
            - name: NEURON_COMPILED_ARTIFACTS
              value: /root/.cache/neuron/deepseek-ai/DeepSeek-R1-Distill-Llama-8B-int8
          ports:
            - name: http
              containerPort: 8000
          ports:
            - name: http
              containerPort: 8000
          {{#if compile}}
          resources:
            requests:
              cpu: 24 #75%
              memory: 96Gi #75%
              aws.amazon.com/neuroncore: 2
            limits:
              aws.amazon.com/neuroncore: 2
          {{else}}
          resources:
            requests:
              cpu: 3 #75%
              memory: 12Gi #75%
              aws.amazon.com/neuroncore: 2
            limits:
              aws.amazon.com/neuroncore: 2
          {{/if}}
          volumeMounts:
            - name: huggingface-cache
              mountPath: /root/.cache/huggingface
            - name: neuron-cache
              mountPath: /root/.cache/neuron
      volumes:
        - name: huggingface-cache
          persistentVolumeClaim:
            claimName: huggingface-cache
        - name: neuron-cache
          persistentVolumeClaim:
            claimName: neuron-cache
      tolerations:
        - key: aws.amazon.com/neuron
          operator: Exists
          effect: NoSchedule
---
apiVersion: v1
kind: Service
metadata:
  name: deepseek-r1-llama-8b-int8-neuron
  namespace: vllm
spec:
  selector:
    app: deepseek-r1-llama-8b-int8-neuron
  ports:
    - name: http
      port: 8000
