apiVersion: apps/v1
kind: Deployment
metadata:
  name: llama-3-1-8b-int8-neuron
  namespace: vllm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: llama-3-1-8b-int8-neuron
  template:
    metadata:
      labels:
        app: llama-3-1-8b-int8-neuron
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      automountServiceAccountToken: false
      nodeSelector:
        eks.amazonaws.com/instance-family: inf2
        {{#if compile}}
        node.kubernetes.io/instance-type: inf2.8xlarge 
        karpenter.sh/capacity-type: on-demand
        {{else}}
        node.kubernetes.io/instance-type: inf2.xlarge
        {{/if}}
      containers:
        - name: vllm
          image: {{{IMAGE}}}
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - NET_RAW
            seccompProfile:
              type: RuntimeDefault
          command: ["vllm", "serve"]
          args:
            {{#if compile}}
            - meta-llama/Llama-3.1-8B-Instruct
            {{else}}
            - {{{modelPath}}}
            {{/if}}
            - --served-model-name=llama-3-1-8b-int8-neuron
            - --trust-remote-code
            - --gpu-memory-utilization=0.90
            # - --max-model-len=32768 # 32K
            # Llama 3.1 specific
            - --enable-auto-tool-choice
            - --tool-call-parser=llama3_json
            - --chat-template=examples/tool_chat_template_llama3.1_json.jinja
            # Neuron specific
            - --tensor-parallel-size=2
            - --max-num-seqs=4
            - --max-model-len=8192 #8K
            {{#unless compile}}
            - '--override-neuron-config={"quantized": true, "quantized_checkpoints_path": "{{{modelPath}}}", "kv_cache_quant": true}'
            {{/unless}}
          env:
            {{#if compile}}
            - name: HUGGING_FACE_HUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: hf-token
                  key: token
            {{/if}}      
            - name: NEURON_COMPILED_ARTIFACTS
              value: {{{neuronPath}}}
          ports:
            - name: http
              containerPort: 8000
          {{#if compile}}
          resources:
            requests:
              cpu: 24 #75%
              memory: 96Gi #75%
              aws.amazon.com/neuroncore: 2
            limits:
              aws.amazon.com/neuroncore: 2
          {{else}}
          resources:
            requests:
              cpu: 3 #75%
              memory: 12Gi #75%
              aws.amazon.com/neuroncore: 2
            limits:
              aws.amazon.com/neuroncore: 2
          {{/if}}
      {{#if compile}}
          volumeMounts:
            - name: huggingface-cache
              mountPath: /root/.cache/huggingface
            - name: neuron-cache
              mountPath: /root/.cache/neuron
      volumes:
        - name: huggingface-cache
          persistentVolumeClaim:
            claimName: huggingface-cache
        - name: neuron-cache
          persistentVolumeClaim:
            claimName: neuron-cache
      {{/if}}
      tolerations:
        - key: aws.amazon.com/neuron
          operator: Exists
          effect: NoSchedule
---
apiVersion: v1
kind: Service
metadata:
  name: llama-3-1-8b-int8-neuron
  namespace: vllm
spec:
  selector:
    app: llama-3-1-8b-int8-neuron
  ports:
    - name: http
      port: 8000
