apiVersion: apps/v1
kind: Deployment
metadata:
  name: qwen3-next-80b-thinking
  namespace: vllm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qwen3-next-80b-thinking
  template:
    metadata:
      labels:
        app: qwen3-next-80b-thinking
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      automountServiceAccountToken: false
      nodeSelector:
        {{{KARPENTER_PREFIX}}}/instance-family: g6e
      containers:
        - name: vllm
          image: {{DOCKER_IMAGE_PREFIX}}vllm/vllm-openai:v0.10.2
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - NET_RAW
            seccompProfile:
              type: RuntimeDefault
          command: ["vllm", "serve"]
          args:
            - Qwen/Qwen3-Next-80B-A3B-Thinking
            - --served-model-name=qwen3-next-80b-thinking
            - --trust-remote-code
            # - --gpu-memory-utilization=0.90
            # - --gpu-memory-utilization=0.95
            # - --max-model-len=32768 # 32K
            # - --max-model-len=16384 # 16K
            - --gpu-memory-utilization=0.95
            - --max-model-len=131072 # 128K
            - --max-num-seqs=4
            - --tensor-parallel-size=4
            # Qwen3 specific
            - --reasoning-parser=qwen3
            - --tokenizer-mode=auto
            - --no-enable-chunked-prefill
            - '--speculative-config={"method": "qwen3_next_mtp", "num_speculative_tokens": 2}'
          env:
            - name: HUGGING_FACE_HUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: hf-token
                  key: token
          ports:
            - name: http
              containerPort: 8000
          resources:
            requests:
              cpu: 36 #75%
              memory: 288Gi #75%
              nvidia.com/gpu: 4
            limits:
              nvidia.com/gpu: 4
          volumeMounts:
            - name: huggingface-cache
              mountPath: /root/.cache/huggingface
            - name: shm
              mountPath: /dev/shm
      volumes:
        - name: huggingface-cache
          persistentVolumeClaim:
            claimName: huggingface-cache
        - name: shm
          emptyDir:
            medium: Memory
            sizeLimit: 10Gi
      tolerations:
        - key: nvidia.com/gpu
          operator: Exists
          effect: NoSchedule
---
apiVersion: v1
kind: Service
metadata:
  name: qwen3-next-80b-thinking
  namespace: vllm
spec:
  selector:
    app: qwen3-next-80b-thinking
  ports:
    - name: http
      port: 8000
