apiVersion: apps/v1
kind: Deployment
metadata:
  name: llama-4-scout-17b-16e-instruct-pf8
  namespace: vllm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: llama-4-scout-17b-16e-instruct-pf8
  template:
    metadata:
      labels:
        app: llama-4-scout-17b-16e-instruct-pf8
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      automountServiceAccountToken: false
      nodeSelector:
        {{{KARPENTER_PREFIX}}}/instance-family: g6e
      containers:
        - name: vllm
          image: vllm/vllm-openai:v0.10.2
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - NET_RAW
            seccompProfile:
              type: RuntimeDefault
          command: ["vllm", "serve"]
          args:
            - RedHatAI/Llama-4-Scout-17B-16E-Instruct-FP8-dynamic
            - --served-model-name=llama-4-scout-17b-16e-instruct-pf8
            - --trust-remote-code
            - --gpu-memory-utilization=0.9
            - --max-model-len=32768 # 32K
            # Llama4 specific
            - --enable-auto-tool-choice
            - --tool-call-parser=llama3_json
            - --chat-template=examples/tool_chat_template_llama3.2_json.jinja
            - --tensor-parallel-size=4 # 4 GPUs
          env:
            - name: HUGGING_FACE_HUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: hf-token
                  key: token
          ports:
            - name: http
              containerPort: 8000
          resources:
            requests:
              cpu: 36 #75%
              memory: 288Gi #75%
              nvidia.com/gpu: 4
            limits:
              nvidia.com/gpu: 4
          volumeMounts:
            - name: huggingface-cache
              mountPath: /root/.cache/huggingface
            - name: shm
              mountPath: /dev/shm
      volumes:
        - name: huggingface-cache
          persistentVolumeClaim:
            claimName: huggingface-cache
        - name: shm
          emptyDir:
            medium: Memory
            sizeLimit: 10Gi
      tolerations:
        - key: nvidia.com/gpu
          operator: Exists
          effect: NoSchedule
---
apiVersion: v1
kind: Service
metadata:
  name: llama-4-scout-17b-16e-instruct-pf8
  namespace: vllm
spec:
  selector:
    app: llama-4-scout-17b-16e-instruct-pf8
  ports:
    - name: http
      port: 8000
