apiVersion: apps/v1
kind: Deployment
metadata:
  name: qwen3-8b-neuron
  namespace: vllm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qwen3-8b-neuron
  template:
    metadata:
      labels:
        app: qwen3-8b-neuron
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      automountServiceAccountToken: false
      nodeSelector:
        {{{KARPENTER_PREFIX}}}/instance-family: inf2
        # node.kubernetes.io/instance-type: inf2.8xlarge 
        # karpenter.sh/capacity-type: on-demand
        {{#if compile}}
        node.kubernetes.io/instance-type: inf2.8xlarge
        karpenter.sh/capacity-type: on-demand
        {{else}}
        node.kubernetes.io/instance-type: inf2.xlarge
        {{/if}}
      containers:
        - name: vllm
          image: public.ecr.aws/t0h7h1e6/vllm-neuron:qwen3-8b
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - NET_RAW
            seccompProfile:
              type: RuntimeDefault
          command: ["vllm", "serve"]
          args:
            - /root/.cache/huggingface/hub/models--Qwen--Qwen3-8B/snapshots/b968826d9c46dd6066d109eabc6255188de91218
            - --served-model-name=qwen3-8b-neuron
            - --trust-remote-code
            - --gpu-memory-utilization=0.90
            # - --max-model-len=32768 # 32K
            # Qwen3 specific
            - --enable-auto-tool-choice
            - --tool-call-parser=hermes
            - --reasoning-parser=qwen3
            # Neuron specific
            - --tensor-parallel-size=2
            # - --gpu-memory-utilization=0.95
            - --max-num-seqs=1
            - --max-model-len=16384
          env:
            {{#if compile}}
            - name: HUGGING_FACE_HUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: hf-token
                  key: token
            {{/if}}
            - name: NEURON_COMPILED_ARTIFACTS
              value: /root/.cache/neuron/Qwen/Qwen3-8B
          ports:
            - name: http
              containerPort: 8000
          {{#if compile}}
          resources:
            requests:
              cpu: 24 #75%
              memory: 96Gi #75%
              aws.amazon.com/neuroncore: 2
            limits:
              aws.amazon.com/neuroncore: 2
          {{else}}
          resources:
            requests:
              cpu: 3 #75%
              memory: 12Gi #75%
              aws.amazon.com/neuroncore: 2
            limits:
              aws.amazon.com/neuroncore: 2
          {{/if}}
      {{#if compile}}
          volumeMounts:
            - name: huggingface-cache
              mountPath: /root/.cache/huggingface
            - name: neuron-cache
              mountPath: /root/.cache/neuron
      volumes:
        - name: huggingface-cache
          persistentVolumeClaim:
            claimName: huggingface-cache
        - name: neuron-cache
          persistentVolumeClaim:
            claimName: neuron-cache
      {{/if}}
      tolerations:
        - key: aws.amazon.com/neuron
          operator: Exists
          effect: NoSchedule
---
apiVersion: v1
kind: Service
metadata:
  name: qwen3-8b-neuron
  namespace: vllm
spec:
  selector:
    app: qwen3-8b-neuron
  ports:
    - name: http
      port: 8000
