
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gpt-oss-120b
  namespace: vllm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gpt-oss-120b
  template:
    metadata:
      labels:
        app: gpt-oss-120b
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      automountServiceAccountToken: false
      nodeSelector:
        {{{KARPENTER_PREFIX}}}/instance-family: g7e
      containers:
        - name: vllm
          image: vllm/vllm-openai:v0.14.1
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - NET_RAW
            seccompProfile:
              type: RuntimeDefault
          command: ["vllm", "serve"]
          args:
            - openai/gpt-oss-120b
            - --served-model-name=gpt-oss-120b
            - --trust-remote-code
            - --gpu-memory-utilization=0.95
            - --max-model-len=131072 # 128K
            # gpt-oss specific
            - --kv-cache-dtype=fp8
            - '--compilation-config={"pass_config":{"fuse_allreduce_rms":true,"eliminate_noops":true}}'
            - --async-scheduling
            - --no-enable-prefix-caching
            - --max-cudagraph-capture-size=2048
            - --max-num-batched-tokens=8192
            - --stream-interval=20
            - --max-num-seqs=2
          env:
            - name: HUGGING_FACE_HUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: hf-token
                  key: token
            - name: VLLM_USE_FLASHINFER_MOE_FP8
              value: "1"
          ports:
            - name: http
              containerPort: 8000
          resources:
            requests:
              cpu: 6 #75%
              memory: 48Gi #75%
              nvidia.com/gpu: 1
            limits:
              nvidia.com/gpu: 1
          volumeMounts:
            - name: huggingface-cache
              mountPath: /root/.cache/huggingface
      volumes:
        - name: huggingface-cache
          persistentVolumeClaim:
            claimName: huggingface-cache
      tolerations:
        - key: nvidia.com/gpu
          operator: Exists
          effect: NoSchedule
---
apiVersion: v1
kind: Service
metadata:
  name: gpt-oss-120b
  namespace: vllm
spec:
  selector:
    app: gpt-oss-120b
  ports:
    - name: http
      port: 8000
