apiVersion: apps/v1
kind: Deployment
metadata:
  name: gpt-oss-20b
  namespace: vllm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gpt-oss-20b
  template:
    metadata:
      labels:
        app: gpt-oss-20b
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      automountServiceAccountToken: false
      nodeSelector:
        {{{KARPENTER_PREFIX}}}/instance-family: g6e
      containers:
        - name: vllm
          image: {{DOCKER_IMAGE_PREFIX}}vllm/vllm-openai:gptoss
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - NET_RAW
            seccompProfile:
              type: RuntimeDefault
          command: ["vllm", "serve"]
          args:
            - openai/gpt-oss-20b
            - --served-model-name=gpt-oss-20b
            - --trust-remote-code
            - --gpu-memory-utilization=0.90
            - --max-model-len=32768 # 32K
            # - --max-model-len=131072 # 128K
          env:
            - name: HUGGING_FACE_HUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: hf-token
                  key: token
            - name: VLLM_ATTENTION_BACKEND
              value: TRITON_ATTN_VLLM_V1
          resources:
            requests:
              cpu: 3 #75%
              memory: 24Gi #75%
              nvidia.com/gpu: 1
            limits:
              nvidia.com/gpu: 1
          volumeMounts:
            - name: huggingface-cache
              mountPath: /root/.cache/huggingface
            - name: shm
              mountPath: /dev/shm
      volumes:
        - name: huggingface-cache
          persistentVolumeClaim:
            claimName: huggingface-cache
        - name: shm
          emptyDir:
            medium: Memory
      tolerations:
        - key: nvidia.com/gpu
          operator: Exists
          effect: NoSchedule
---
apiVersion: v1
kind: Service
metadata:
  name: gpt-oss-20b
  namespace: vllm
spec:
  selector:
    app: gpt-oss-20b
  ports:
    - name: http
      port: 8000
