apiVersion: apps/v1
kind: Deployment
metadata:
  name: magistral-24b-fp8
  namespace: vllm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: magistral-24b-fp8
  template:
    metadata:
      labels:
        app: magistral-24b-fp8
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      automountServiceAccountToken: false
      nodeSelector:
        {{{KARPENTER_PREFIX}}}/instance-family: g6e
      containers:
        - name: vllm
          image: {{DOCKER_IMAGE_PREFIX}}vllm/vllm-openai:v0.10.2
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - NET_RAW
            seccompProfile:
              type: RuntimeDefault
          command: ["vllm", "serve"]
          args:
            - RedHatAI/Magistral-Small-2506-FP8
            - --served-model-name=magistral-24b-fp8
            - --trust-remote-code
            - --gpu-memory-utilization=0.90
            - --max-model-len=32768 # 32K
            # Mistral specific
            - --enable-auto-tool-choice
            - --tool-call-parser=mistral
            - --chat-template=examples/tool_chat_template_mistral.jinja
            - --tokenizer-mode=mistral
            - --load-format=mistral
            - --config-format=mistral
          env:
            - name: HUGGING_FACE_HUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: hf-token
                  key: token
          ports:
            - name: http
              containerPort: 8000
          resources:
            requests:
              cpu: 3 #75%
              memory: 24Gi #75%
              nvidia.com/gpu: 1
            limits:
              nvidia.com/gpu: 1
          volumeMounts:
            - name: huggingface-cache
              mountPath: /root/.cache/huggingface
      volumes:
        - name: huggingface-cache
          persistentVolumeClaim:
            claimName: huggingface-cache
      tolerations:
        - key: nvidia.com/gpu
          operator: Exists
          effect: NoSchedule
---
apiVersion: v1
kind: Service
metadata:
  name: magistral-24b-fp8
  namespace: vllm
spec:
  selector:
    app: magistral-24b-fp8
  ports:
    - name: http
      port: 8000
