apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculator
  namespace: mcp-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: calculator
  template:
    metadata:
      labels:
        app: calculator
    spec:
      {{#unless useBuildx}}
      nodeSelector:
        kubernetes.io/arch: {{{arch}}}
      {{/unless}}
      containers:
        - name: server
          image: {{{IMAGE}}}
          ports:
            - name: http
              containerPort: 8000
          resources:
            requests:
              cpu: 250m 
              memory: 512Mi
            limits:
              memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: calculator
  namespace: mcp-server
spec:
  selector:
    app: calculator
  ports:
    - name: http
      port: 8000

