apiVersion: v1
kind: ServiceAccount
metadata:
  name: buildkit
  namespace: vllm
automountServiceAccountToken: false
---
apiVersion: v1
kind: Pod
metadata:
  name: buildkit
  namespace: vllm
spec:
  serviceAccountName: buildkit
  automountServiceAccountToken: false
  nodeSelector:
    karpenter.sh/nodepool: builder-bottlerocket
    karpenter.sh/capacity-type: on-demand
    node.kubernetes.io/instance-type: r7i.2xlarge
  containers:
    - name: buildkit
      image: moby/buildkit:v0.25.1
      securityContext:
        privileged: true
        allowPrivilegeEscalation: true
        runAsUser: 0
      tty: true
      stdin: true
      resources:
        requests:
          cpu: 3.6
          memory: 29Gi
        limits:
          memory: 60Gi
      volumeMounts:
        - name: huggingface-cache
          mountPath: /root/.cache/huggingface
        - name: neuron-cache
          mountPath: /root/.cache/neuron
  volumes:
    - name: huggingface-cache
      persistentVolumeClaim:
        claimName: huggingface-cache
    - name: neuron-cache
      persistentVolumeClaim:
        claimName: neuron-cache
