apiVersion: apps/v1
kind: Deployment
metadata:
  name: qwen3-embedding-06b-bf16
  namespace: tei
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qwen3-embedding-06b-bf16
  template:
    metadata:
      labels:
        app: qwen3-embedding-06b-bf16
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      automountServiceAccountToken: false
      nodeSelector:
        {{{KARPENTER_PREFIX}}}/instance-family: g6
      containers:
        - name: tei
          image: ghcr.io/huggingface/text-embeddings-inference:1.8
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - NET_RAW
            seccompProfile:
              type: RuntimeDefault
          args:
            - --model-id=Qwen/Qwen3-Embedding-0.6B
            - --huggingface-hub-cache=/root/.cache/huggingface/hub
          env:
            - name: HF_TOKEN
              valueFrom:
                secretKeyRef:
                  name: hf-token
                  key: token
          ports:
            - name: http
              containerPort: 80
          resources:
            requests:
              cpu: 3 #75%
              memory: 12Gi #75%
              nvidia.com/gpu: 1
            limits:
              nvidia.com/gpu: 1
          volumeMounts:
            - name: huggingface-cache
              mountPath: /root/.cache/huggingface
            - name: shm
              mountPath: /dev/shm
      volumes:
        - name: huggingface-cache
          persistentVolumeClaim:
            claimName: huggingface-cache
        - name: shm
          emptyDir:
            medium: Memory
            sizeLimit: 10Gi
      tolerations:
        - key: nvidia.com/gpu
          operator: Exists
          effect: NoSchedule
---
apiVersion: v1
kind: Service
metadata:
  name: qwen3-embedding-06b-bf16
  namespace: tei
spec:
  selector:
    app: qwen3-embedding-06b-bf16
  ports:
    - name: http
      port: 80
