apiVersion: apps/v1
kind: Deployment
metadata:
  name: qwen3-embedding-8b-bf16-cpu
  namespace: tei
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qwen3-embedding-8b-bf16-cpu
  template:
    metadata:
      labels:
        app: qwen3-embedding-8b-bf16-cpu
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      automountServiceAccountToken: false
      nodeSelector:
        kubernetes.io/arch: amd64
        # karpenter.sh/capacity-type: on-demand
        # eks.amazonaws.com/instance-category: r
        # eks.amazonaws.com/instance-generation: "7"
        eks.amazonaws.com/instance-family: r7i
        # node.kubernetes.io/instance-type: r7i.2xlarge
      containers:
        - name: tei
          image: ghcr.io/huggingface/text-embeddings-inference@sha256:49b0916457823f64ebf0ce79b37ec0031da27b579c83c623dad7a2812f277cd4
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - NET_RAW
            seccompProfile:
              type: RuntimeDefault
          args:
            - --model-id=Qwen/Qwen3-Embedding-8B
            - --huggingface-hub-cache=/root/.cache/huggingface
          env:
            - name: HF_TOKEN
              valueFrom:
                secretKeyRef:
                  name: hf-token
                  key: token
          ports:
            - name: http
              containerPort: 80
          resources:
            requests:
              cpu: 7.2 #90%
              memory: 58Gi #90%
            limits:
              cpu: 7.2 #90%
              memory: 58Gi #90%
          volumeMounts:
            - name: huggingface-cache
              mountPath: /root/.cache/huggingface
            - name: shm
              mountPath: /dev/shm
      volumes:
        - name: huggingface-cache
          persistentVolumeClaim:
            claimName: huggingface-cache
        - name: shm
          emptyDir:
            medium: Memory
            sizeLimit: 10Gi
      tolerations:
        - key: nvidia.com/gpu
          operator: Exists
          effect: NoSchedule
---
apiVersion: v1
kind: Service
metadata:
  name: qwen3-embedding-8b-bf16-cpu
  namespace: tei
spec:
  selector:
    app: qwen3-embedding-8b-bf16-cpu
  ports:
    - name: http
      port: 80
