apiVersion: apps/v1
kind: Deployment
metadata:
  name: qwen3-embedding-06b-bf16-cpu
  namespace: tei
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qwen3-embedding-06b-bf16-cpu
  template:
    metadata:
      labels:
        app: qwen3-embedding-06b-bf16-cpu
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      automountServiceAccountToken: false
      nodeSelector:
        kubernetes.io/arch: amd64
        # karpenter.sh/capacity-type: on-demand
        # eks.amazonaws.com/instance-category: m
        # eks.amazonaws.com/instance-generation: "7"
        eks.amazonaws.com/instance-family: m7i
        # node.kubernetes.io/instance-type: m7i.large
      containers:
        - name: tei
          image: ghcr.io/huggingface/text-embeddings-inference:cpu-1.8
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - NET_RAW
            seccompProfile:
              type: RuntimeDefault
          args:
            - --model-id=Qwen/Qwen3-Embedding-0.6B
            - --huggingface-hub-cache=/root/.cache/huggingface
          env:
            - name: HF_TOKEN
              valueFrom:
                secretKeyRef:
                  name: hf-token
                  key: token
          ports:
            - name: http
              containerPort: 80
          resources:
            requests:
              cpu: 1.6 #80%
              memory: 6Gi #80%
            limits:
              cpu: 1.6 #80%
              memory: 6Gi #80%
          volumeMounts:
            - name: huggingface-cache
              mountPath: /root/.cache/huggingface
            - name: shm
              mountPath: /dev/shm
      volumes:
        - name: huggingface-cache
          persistentVolumeClaim:
            claimName: huggingface-cache
        - name: shm
          emptyDir:
            medium: Memory
            sizeLimit: 10Gi
      tolerations:
        - key: nvidia.com/gpu
          operator: Exists
          effect: NoSchedule
---
apiVersion: v1
kind: Service
metadata:
  name: qwen3-embedding-06b-bf16-cpu
  namespace: tei
spec:
  selector:
    app: qwen3-embedding-06b-bf16-cpu
  ports:
    - name: http
      port: 80
