apiVersion: apps/v1
kind: Deployment
metadata:
  name: qwen3-30b-thinking-fp8
  namespace: sglang
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qwen3-30b-thinking-fp8
  template:
    metadata:
      labels:
        app: qwen3-30b-thinking-fp8
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      automountServiceAccountToken: false
      nodeSelector:
        eks.amazonaws.com/instance-family: g6e
      containers:
        - name: sglang
          image: docker.io/lmsysorg/sglang:v0.4.10.post2-cu126
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - NET_RAW
            seccompProfile:
              type: RuntimeDefault
          command: ["python3", "-m", "sglang.launch_server"]
          args:
            - --model-path=Qwen/Qwen3-30B-A3B-Thinking-2507-FP8
            - --host=0.0.0.0
            - --port=30000
            - --trust-remote-code
            - --mem-fraction-static=0.90
            - --context-length=32768 # 32K
            # Qwen3 specific
            - --reasoning-parser=qwen3
          env:
            - name: HF_TOKEN
              valueFrom:
                secretKeyRef:
                  name: hf-token
                  key: token
          ports:
            - name: http
              containerPort: 30000
          resources:
            requests:
              cpu: 3 #75%
              memory: 24Gi #75%
              nvidia.com/gpu: 1
            limits:
              nvidia.com/gpu: 1
          volumeMounts:
            - name: huggingface-cache
              mountPath: /root/.cache/huggingface
            - name: shm
              mountPath: /dev/shm
      volumes:
        - name: huggingface-cache
          persistentVolumeClaim:
            claimName: huggingface-cache
        - name: shm
          emptyDir:
            medium: Memory
            sizeLimit: 10Gi
      tolerations:
        - key: nvidia.com/gpu
          operator: Exists
          effect: NoSchedule
---
apiVersion: v1
kind: Service
metadata:
  name: qwen3-30b-thinking-fp8
  namespace: sglang
spec:
  selector:
    app: qwen3-30b-thinking-fp8
  ports:
    - name: http
      port: 30000
