apiVersion: apps/v1
kind: Deployment
metadata:
  name: qwen3-coder-480b-fp8
  namespace: sglang
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qwen3-coder-480b-fp8
  template:
    metadata:
      labels:
        app: qwen3-coder-480b-fp8
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      automountServiceAccountToken: false
      nodeSelector:
        # {{{KARPENTER_PREFIX}}}/instance-family: p4de
        {{{KARPENTER_PREFIX}}}/instance-category: p
        # {{{KARPENTER_PREFIX}}}/instance-generation: "5"
        # karpenter.sh/capacity-type: on-demand
        # {{{KARPENTER_PREFIX}}}/instance-gpu-name: h200
      containers:
        - name: sglang
          image: docker.io/lmsysorg/sglang:v0.4.10.post2-cu126
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - NET_RAW
            seccompProfile:
              type: RuntimeDefault
          command: ["python3", "-m", "sglang.launch_server"]
          args:
            - --model-path=Qwen/Qwen3-Coder-480B-A35B-Instruct-FP8
            - --host=0.0.0.0
            - --port=30000
            - --trust-remote-code
            - --mem-fraction-static=0.90
            # - --context-length=32768 # 32K
            - --context-length=262144 #256K
            - --tp-size=8
            - --ep-size=8
            # Qwen3 specific
            - --tool-call-parser=qwen25
            - --reasoning-parser=qwen3
          env:
            - name: HF_TOKEN
              valueFrom:
                secretKeyRef:
                  name: hf-token
                  key: token
          ports:
            - name: http
              containerPort: 30000
          resources:
            requests:
              # cpu: 144 #75%
              # memory: 1536Gi #75%
              nvidia.com/gpu: 8
            limits:
              nvidia.com/gpu: 8
          volumeMounts:
            - name: huggingface-cache
              mountPath: /root/.cache/huggingface
            - name: shm
              mountPath: /dev/shm
      volumes:
        - name: huggingface-cache
          persistentVolumeClaim:
            claimName: huggingface-cache
        - name: shm
          emptyDir:
            medium: Memory
            sizeLimit: 100Gi
      tolerations:
        - key: nvidia.com/gpu
          operator: Exists
          effect: NoSchedule
---
apiVersion: v1
kind: Service
metadata:
  name: qwen3-coder-480b-fp8
  namespace: sglang
spec:
  selector:
    app: qwen3-coder-480b-fp8
  ports:
    - name: http
      port: 30000
