apiVersion: v1
kind: Pod
metadata:
  name: builder-optimum-neuron
  namespace: vllm
  # namespace: sglang
  # namespace: tgi
spec:
  nodeSelector:
    # karpenter.sh/nodepool: custom
    karpenter.sh/capacity-type: on-demand
    node.kubernetes.io/instance-type: inf2.8xlarge
  containers:
    - name: ubuntu
      image: ghcr.io/huggingface/optimum-neuron-vllm:0.4.1
      command: ["/bin/bash"]
      args: ["-c", "while true; do sleep 30; done;"]
      tty: true
      stdin: true
      env:
        - name: HUGGING_FACE_HUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: hf-token
              key: token
        - name: HF_HOME
          value: /root/.cache/huggingface
        - name: HF_HUB_CACHE
          value: /root/.cache/huggingface/hub
        - name: NEURON_RT_NUM_CORES
          value: "2"
        - name: NEURON_RT_VISIBLE_CORES
          value: "0-1"
      resources:
        requests:
          cpu: 24 #75%
          memory: 96Gi #75%
          aws.amazon.com/neuroncore: 2
        limits:
          aws.amazon.com/neuroncore: 2
      volumeMounts:
        - name: huggingface-cache
          mountPath: /root/.cache/huggingface
        - name: neuron-cache
          mountPath: /root/.cache/neuron
  volumes:
    - name: huggingface-cache
      persistentVolumeClaim:
        claimName: huggingface-cache
    - name: shm
      emptyDir:
        medium: Memory
    - name: neuron-cache
      persistentVolumeClaim:
        claimName: neuron-cache
  tolerations:
    # - key: karpenter.sh/nodepool
    #   operator: Equal
    #   value: custom
    #   effect: NoSchedule
    - key: aws.amazon.com/neuron
      operator: Exists
      effect: NoSchedule
# Terminal 1
