apiVersion: apps/v1
kind: Deployment
metadata:
  name: llama-3-1-8b-neuron
  namespace: vllm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: llama-3-1-8b-neuron
  template:
    metadata:
      labels:
        app: llama-3-1-8b-neuron
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      automountServiceAccountToken: false
      nodeSelector:
        {{{KARPENTER_PREFIX}}}/instance-family: inf2
        # node.kubernetes.io/instance-type: inf2.8xlarge 
        # karpenter.sh/capacity-type: on-demand
      containers:
        - name: vllm
          image: public.ecr.aws/neuron/pytorch-inference-vllm-neuronx:0.9.1-neuronx-py311-sdk2.26.0-ubuntu22.04
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - NET_RAW
            seccompProfile:
              type: RuntimeDefault
          command: ["vllm", "serve"]
          args:
            - meta-llama/Llama-3.1-8B-Instruct
            - --served-model-name=llama-3-1-8b-neuron
            - --trust-remote-code
            # - --gpu-memory-utilization=0.90
            # - --max-model-len=32768 # 32K
            # Llama 3.1 specific
            - --enable-auto-tool-choice
            - --tool-call-parser=llama3_json
            - --chat-template=examples/tool_chat_template_llama3.1_json.jinja
            # Neuron specific
            - --tensor-parallel-size=2
            - --gpu-memory-utilization=0.95
            - --max-num-seqs=3
            - --max-model-len=8192
          env:
            - name: HUGGING_FACE_HUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: hf-token
                  key: token
            - name: NEURON_COMPILED_ARTIFACTS
              value: /root/.cache/neuron/meta-llama/Llama-3.1-8B-Instruct
          ports:
            - name: http
              containerPort: 8000
          resources:
            requests:
              cpu: 24 #75%
              memory: 96Gi #75%
              aws.amazon.com/neuroncore: 2
            limits:
              aws.amazon.com/neuroncore: 2
          volumeMounts:
            - name: huggingface-cache
              mountPath: /root/.cache/huggingface
            - name: neuron-cache
              mountPath: /root/.cache/neuron
      volumes:
        - name: huggingface-cache
          persistentVolumeClaim:
            claimName: huggingface-cache
        - name: neuron-cache
          persistentVolumeClaim:
            claimName: neuron-cache
      tolerations:
        - key: aws.amazon.com/neuron
          operator: Exists
          effect: NoSchedule
---
apiVersion: v1
kind: Service
metadata:
  name: llama-3-1-8b-neuron
  namespace: vllm
spec:
  selector:
    app: llama-3-1-8b-neuron
  ports:
    - name: http
      port: 8000
