image:
  registry: quay.io
  repository: keycloak/keycloak
  tag: 26.3

auth:
  adminUser: {{{KEYCLOAK_ADMIN_USER}}}
  adminPassword: {{{KEYCLOAK_ADMIN_PASSWORD}}}

production: false
proxy: edge

resources:
  requests:
    cpu: 500m
    memory: 512Mi
  limits:
    memory: 1Gi

postgresql:
  enabled: true
  image:
    registry: public.ecr.aws
    repository: bitnami/postgresql
    tag: 17.5.0-debian-12-r8
  auth:
    postgresPassword: keycloak-pg-pass
    database: keycloak
  primary:
    resources:
      requests:
        cpu: 125m
        memory: 256Mi
      limits:
        memory: 256Mi

ingress:
  enabled: false
