global:
  security:
    # -- Allow insecure images to use our ECR images.
    allowInsecureImages: true

langfuse:
  salt:
    value: salt
  nextauth:
    secret:
      value: secret
  encryptionKey:
    value: 7188cd4d31f5b0470ed96fa34615a3e779f3a71d1d0f68fc5c166b1c6e515c59 # Dummy key
  ingress:
    enabled: true
    annotations:
      alb.ingress.kubernetes.io/target-type: ip
      {{#if DOMAIN}}
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
      {{/if}}
    hosts:
      - paths:
          - path: /
            pathType: Prefix
        {{#if DOMAIN}}
        host: langfuse.{{{DOMAIN}}}
        {{/if}}

  additionalEnv:
    - name: LANGFUSE_INIT_ORG_ID
      value: my-org
    - name: LANGFUSE_INIT_PROJECT_ID
      value: my-project
    - name: LANGFUSE_INIT_PROJECT_PUBLIC_KEY
      value: {{{LANGFUSE_PUBLIC_KEY}}}
    - name: LANGFUSE_INIT_PROJECT_SECRET_KEY
      value: {{{LANGFUSE_SECRET_KEY}}}
    - name: LANGFUSE_INIT_USER_EMAIL
      value: {{{LANGFUSE_USERNAME}}}
    - name: LANGFUSE_INIT_USER_PASSWORD
      value: {{{LANGFUSE_PASSWORD}}}
  resources:
    requests:
      cpu: 1 
      memory: 2Gi
    limits:
      memory: 2Gi

postgresql:
  image:
    registry: public.ecr.aws
    repository: agentic-ai-platforms-on-k8s/postgresql
    tag: 17.5.0-debian-12-r8
    pullPolicy: IfNotPresent
  auth:
    username: admin
    password: password123
  primary:
    resources: 
      requests:
        cpu: 125m
        memory: 256Mi
      limits:
        memory: 256Mi

clickhouse:
  image:
    registry: public.ecr.aws
    repository: agentic-ai-platforms-on-k8s/clickhouse
    tag: 25.2.1-debian-12-r0
    pullPolicy: IfNotPresent
  auth:
    password: password123
  replicaCount: 1
  resources:
    requests:
      cpu: 1    
      memory: 3Gi
      ephemeral-storage: 50Mi
    limits:
      memory: 3Gi
      ephemeral-storage: 2Gi
  zookeeper:
    image:
      registry: public.ecr.aws
      repository: agentic-ai-platforms-on-k8s/zookeeper
      tag: 3.9.3-debian-12-r8
      pullPolicy: IfNotPresent
    replicaCount: 1
    resources: 
      requests:
        cpu: 250m    
        memory: 384Mi
        ephemeral-storage: 50Mi
      limits:
        memory: 384Mi
        ephemeral-storage: 2Gi 

redis:
  image:
    registry: public.ecr.aws
    repository: agentic-ai-platforms-on-k8s/valkey
    tag: 8.0.2-debian-12-r2
    pullPolicy: IfNotPresent
  auth:
    password: password123
  primary:
    resources: 
      requests:
        cpu: 125m
        memory: 256Mi
      limits:
        memory: 256Mi

s3:
  deploy: false

  bucket: "{{LANGFUSE_BUCKET_NAME}}"
  region: "{{AWS_REGION}}"
  endpoint: "" 
  forcePathStyle: false

  eventUpload:
    bucket: "{{LANGFUSE_BUCKET_NAME}}"
    prefix: "events/"
    region: "{{AWS_REGION}}"

  batchExport:
    enabled: true
    bucket: "{{LANGFUSE_BUCKET_NAME}}"
    prefix: "batch-exports/"
    region: "{{AWS_REGION}}"

  mediaUpload:
    enabled: true
    bucket: "{{LANGFUSE_BUCKET_NAME}}"
    prefix: "media/"
    region: "{{AWS_REGION}}"
