apiVersion: apps/v1
kind: Deployment
metadata:
  name: doc-writer
  namespace: openclaw
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: doc-writer
  template:
    metadata:
      labels:
        app: doc-writer
    spec:
      serviceAccountName: doc-writer
      automountServiceAccountToken: false
      {{#unless useBuildx}}
      nodeSelector:
        kubernetes.io/arch: {{{arch}}}
      {{/unless}}
      containers:
        - name: agent
          image: {{{IMAGE}}}
          imagePullPolicy: Always
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            allowPrivilegeEscalation: false
          env:
            - name: OPENCLAW_GATEWAY_TOKEN
              value: "{{{OPENCLAW_GATEWAY_TOKEN}}}"
            - name: LITELLM_BASE_URL
              value: {{{LITELLM_BASE_URL}}}
            - name: LITELLM_API_KEY
              value: "{{{LITELLM_API_KEY}}}"
            - name: LITELLM_MODEL_NAME
              value: {{{LITELLM_MODEL_NAME}}}
            {{#if GIT_REPO_URL}}
            - name: GIT_REPO_URL
              value: "{{{GIT_REPO_URL}}}"
            {{/if}}
            {{#if LANGFUSE_HOST}}
            - name: LANGFUSE_HOST
              value: {{{LANGFUSE_HOST}}}
            - name: LANGFUSE_PUBLIC_KEY
              value: {{{LANGFUSE_PUBLIC_KEY}}}
            - name: LANGFUSE_SECRET_KEY
              value: {{{LANGFUSE_SECRET_KEY}}}
            {{/if}}
          ports:
            - name: http
              containerPort: 8080
          resources:
            requests:
              cpu: 250m
              memory: 1Gi
            limits:
              cpu: 1000m
              memory: 2Gi
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: doc-writer
  namespace: openclaw
spec:
  selector:
    app: doc-writer
  ports:
    - name: http
      port: 8080
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: doc-writer
  namespace: openclaw
automountServiceAccountToken: false
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: doc-writer-scaler
  namespace: openclaw
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: doc-writer
  minReplicaCount: 0
  maxReplicaCount: 5
  cooldownPeriod: 300
  triggers:
  - type: cpu
    metricType: Utilization
    metadata:
      value: "50"
