apiVersion: apps/v1
kind: Deployment
metadata:
  name: qwen3-8b-fp8
  namespace: tgi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qwen3-8b-fp8
  template:
    metadata:
      labels:
        app: qwen3-8b-fp8
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      automountServiceAccountToken: false
      nodeSelector:
        eks.amazonaws.com/instance-family: g6e
      containers:
        - name: tgi
          image: ghcr.io/huggingface/text-generation-inference:3.3.4
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - NET_RAW
            seccompProfile:
              type: RuntimeDefault
          args:
            - --model-id=Qwen/Qwen3-8B-FP8
            - --trust-remote-code
            - --huggingface-hub-cache=/root/.cache/huggingface/hub
          env:
            - name: HF_TOKEN
              valueFrom:
                secretKeyRef:
                  name: hf-token
                  key: token
            - name: CUDA_GRAPHS
              value: "0"
          ports:
            - name: http
              containerPort: 80
          resources:
            requests:
              cpu: 3.6 #90%
              memory: 29Gi #90%
              nvidia.com/gpu: 1
            limits:
              memory: 29Gi #90%
              nvidia.com/gpu: 1
          volumeMounts:
            - name: huggingface-cache
              mountPath: /root/.cache/huggingface
      volumes:
        - name: huggingface-cache
          persistentVolumeClaim:
            claimName: huggingface-cache
      tolerations:
        - key: nvidia.com/gpu
          operator: Exists
          effect: NoSchedule
---
apiVersion: v1
kind: Service
metadata:
  name: qwen3-8b-fp8
  namespace: tgi
spec:
  selector:
    app: qwen3-8b-fp8
  ports:
    - name: http
      port: 80
