apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: neuron-cache
  namespace: tgi
spec:
  storageClassName: efs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi # Dummy
