apiVersion: eks.amazonaws.com/v1
kind: NodeClass
metadata:
  name: custom
spec:
  subnetSelectorTerms:
    - tags:
        Name: "genai-on-eks-private-*"
  securityGroupSelectorTerms:
    - tags:
        "aws:eks:cluster-name": genai-on-eks
  role: genai-on-eks-eks-auto-<SUFFIX>
  ephemeralStorage:
    size: 500Gi
---
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: custom
spec:
  disruption:
    budgets:
      - nodes: 100%
        reasons:
          - Empty
      - nodes: 0%
        reasons:
          - Underutilized
          - Drifted
    consolidateAfter: 30s
    consolidationPolicy: WhenEmptyOrUnderutilized
  template:
    spec:
      expireAfter: 336h
      nodeClassRef:
        group: eks.amazonaws.com
        kind: NodeClass
        name: custom
      requirements:
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["on-demand"]
        - key: kubernetes.io/arch
          operator: In
          values: ["amd64"]
        - key: kubernetes.io/os
          operator: In
          values: ["linux"]
      terminationGracePeriod: 24h0m0s
