apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-agent
  namespace: openclaw
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: devops-agent
  template:
    metadata:
      labels:
        app: devops-agent
    spec:
      serviceAccountName: devops-agent
      automountServiceAccountToken: false
      {{#unless useBuildx}}
      nodeSelector:
        kubernetes.io/arch: {{{arch}}}
      {{/unless}}
      containers:
        - name: agent
          image: {{{IMAGE}}}
          env:
            - name: OPENCLAW_GATEWAY_TOKEN
              value: "{{{OPENCLAW_GATEWAY_TOKEN}}}"
            - name: LITELLM_BASE_URL
              value: {{{LITELLM_BASE_URL}}}
            - name: LITELLM_API_KEY
              value: "{{{LITELLM_API_KEY}}}"
            - name: LITELLM_MODEL_NAME
              value: {{{LITELLM_MODEL_NAME}}}
            {{#if LANGFUSE_HOST}}
            - name: LANGFUSE_HOST
              value: {{{LANGFUSE_HOST}}}
            - name: LANGFUSE_PUBLIC_KEY
              value: {{{LANGFUSE_PUBLIC_KEY}}}
            - name: LANGFUSE_SECRET_KEY
              value: {{{LANGFUSE_SECRET_KEY}}}
            {{/if}}
          ports:
            - name: http
              containerPort: 8080
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              memory: 2Gi
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 90
            periodSeconds: 30
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: devops-agent
  namespace: openclaw
spec:
  selector:
    app: devops-agent
  ports:
    - name: http
      port: 8080
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: devops-agent
  namespace: openclaw
automountServiceAccountToken: false
