apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-agent
  namespace: openclaw
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: devops-agent
  template:
    metadata:
      labels:
        app: devops-agent
    spec:
      serviceAccountName: devops-agent
      automountServiceAccountToken: true
      {{#unless useBuildx}}
      nodeSelector:
        kubernetes.io/arch: {{{arch}}}
      {{/unless}}
      containers:
        - name: agent
          image: {{{IMAGE}}}
          imagePullPolicy: Always
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            allowPrivilegeEscalation: false
          env:
            - name: OPENCLAW_GATEWAY_TOKEN
              value: "{{{OPENCLAW_GATEWAY_TOKEN}}}"
            - name: LITELLM_BASE_URL
              value: {{{LITELLM_BASE_URL}}}
            - name: LITELLM_API_KEY
              value: "{{{LITELLM_API_KEY}}}"
            - name: LITELLM_MODEL_NAME
              value: {{{LITELLM_MODEL_NAME}}}
            {{#if LANGFUSE_HOST}}
            - name: LANGFUSE_HOST
              value: {{{LANGFUSE_HOST}}}
            - name: LANGFUSE_PUBLIC_KEY
              value: {{{LANGFUSE_PUBLIC_KEY}}}
            - name: LANGFUSE_SECRET_KEY
              value: {{{LANGFUSE_SECRET_KEY}}}
            {{/if}}
          ports:
            - name: http
              containerPort: 8080
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              cpu: 2000m
              memory: 2Gi
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: devops-agent
  namespace: openclaw
spec:
  selector:
    app: devops-agent
  ports:
    - name: http
      port: 8080
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: devops-agent
  namespace: openclaw
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: devops-agent-reader
rules:
- apiGroups: ["", "apps", "batch", "networking.k8s.io", "autoscaling"]
  resources: ["pods", "services", "deployments", "replicasets", "statefulsets", "daemonsets", "jobs", "cronjobs", "ingresses", "configmaps", "namespaces", "nodes", "events", "horizontalpodautoscalers"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: devops-agent-reader-binding
subjects:
- kind: ServiceAccount
  name: devops-agent
  namespace: openclaw
roleRef:
  kind: ClusterRole
  name: devops-agent-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: devops-agent
  namespace: openclaw
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: devops-agent
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
