apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io/target-type: ip
    {{#if DOMAIN}}
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
    {{/if}}
  name: ollama
  namespace: ollama
spec:
  rules:
    - http:
        paths:
          - backend:
              service:
                name: ollama
                port:
                  name: http
            path: /
            pathType: Prefix
      {{#if DOMAIN}}
      host: ollama.{{{DOMAIN}}}
      {{/if}}            