apiVersion: v1
kind: ServiceAccount
metadata:
  name: buildkit
  namespace: litellm
automountServiceAccountToken: false
---
apiVersion: v1
kind: Pod
metadata:
  name: buildkit
  namespace: litellm
spec:
  serviceAccountName: buildkit
  automountServiceAccountToken: false
  nodeSelector:
    karpenter.sh/nodepool: builder-bottlerocket
    karpenter.sh/capacity-type: on-demand
    node.kubernetes.io/instance-type: r7i.2xlarge
  containers:
    - name: buildkit
      image: moby/buildkit:v0.25.1
      securityContext:
        privileged: true
        allowPrivilegeEscalation: true
        runAsUser: 0
      tty: true
      stdin: true
      resources:
        requests:
          cpu: 7.2
          memory: 58Gi
        limits:
          memory: 58Gi
