ingress:
  enabled: true
  annotations:
    alb.ingress.kubernetes.io/group.name: default
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
  hosts:
    - host: n8n.{{{DOMAIN}}}
      paths: ["/"]
  tls: []

main:
  resources:
    requests:
      cpu: 1 
      memory: 2Gi
    limits:
      memory: 2Gi
